{% macro query_comment(include_performance_metrics=false, custom_metadata={}) %}
  {# This macro dynamically generates SQL comments with metadata #}
  {# Arguments are documented in query_comment.yml for macro validation testing #}
  
  {% set comment_parts = [] %}
  
  {# Add basic execution metadata #}
  {% set comment_parts = comment_parts + [
    "/* Model: " ~ this.identifier ~ " */",
    "/* Schema: " ~ this.schema ~ " */", 
    "/* Database: " ~ this.database ~ " */",
    "/* Target: " ~ target.name ~ " */",
    "/* Run Started: " ~ run_started_at.strftime('%Y-%m-%d %H:%M:%S') ~ " */",
    "/* Invocation ID: " ~ invocation_id ~ " */"
  ] %}
  
  {# Add environment-specific metadata #}
  {% if target.name == 'prod' %}
    {% set comment_parts = comment_parts + [
      "/* PRODUCTION ENVIRONMENT - CRITICAL DATA */",
      "/* SLA: High Performance Required */",
      "/* Monitoring: Enabled */",
      "/* Backup: Daily */"
    ] %}
  {% elif target.name == 'dev' %}
    {% set comment_parts = comment_parts + [
      "/* DEVELOPMENT ENVIRONMENT */",
      "/* Developer: " ~ var('developer_name', 'Unknown') ~ " */",
      "/* Purpose: Testing and Development */"
    ] %}
  {% endif %}
  
  {# Add model-specific metadata #}
  {% if model %}
    {% set comment_parts = comment_parts + [
      "/* dbt Model Name: " ~ model.name ~ " */",
      "/* dbt Model Path: " ~ model.original_file_path ~ " */",
      "/* dbt Package: " ~ model.package_name ~ " */"
    ] %}
    
    {% if model.config.materialized %}
      {% set comment_parts = comment_parts + [
        "/* Materialization: " ~ model.config.materialized ~ " */"
      ] %}
    {% endif %}
  {% endif %}
  
  {# Add compliance and audit trail #}
  {% set comment_parts = comment_parts + [
    "/* Generated by dbt version: " ~ dbt_version ~ " */",
    "/* Query execution logged for audit purposes */",
    "/* Data lineage tracked automatically */",
    "/* GDPR Compliance: Data processing logged */"
  ] %}
  
  {# Add performance monitoring comments based on argument #}
  {% if include_performance_metrics or var('enable_performance_monitoring', false) %}
    {% set comment_parts = comment_parts + [
      "/* Performance Monitoring: ENABLED */",
      "/* Query ID: " ~ invocation_id ~ "-" ~ this.identifier ~ " */",
      "/* Start Time: " ~ run_started_at ~ " */",
      "/* Expected SLA: " ~ var('query_sla_seconds', '300') ~ " seconds */",
      "/* Macro Args Validation: " ~ flags.validate_macro_args ~ " */"
    ] %}
  {% endif %}
  
  {# Add custom metadata if provided #}
  {% if custom_metadata %}
    {% set comment_parts = comment_parts + ["/* Custom Metadata: */"] %}
    {% for key, value in custom_metadata.items() %}
      {% set comment_parts = comment_parts + ["/* " ~ key ~ ": " ~ value ~ " */"] %}
    {% endfor %}
  {% endif %}
  
  {# Return the complete comment block #}
  {{ comment_parts | join('\n') }}
  
{% endmacro %}
